### PR TITLE
chore: changed github and discord icon to match the brand guidelines

### PR DESCRIPTION
**Pull request by Fedox-die-Ente**
https://github.com/logos
https://discord.com/branding

### CODE REVIEW

**Comment by Fedox-die-Ente** [comment]
see #357

**Comment by abernier** [comment]
actually you're still using a not-official version of the logo. You just switch to another/maybe closer but still customed version of the logo.

image

**Comment by abernier** [comment]
same remark here: I don't understand how these are more "official" than others...

**Comment by Fedox-die-Ente** [comment]
These are the official icons. Just read the Brand Guidelines lol, but okay

**Comment by abernier** [comment]
these ones seem kinda "official" https://react-icons.github.io/react-icons/icons/go/

why did you close the PR? The issue you raised is totally fine as soon as we don't set another non-official icon by another non-official one, that's my point

**Comment by Fedox-die-Ente** [comment]
> these ones seem kinda "official" https://react-icons.github.io/react-icons/icons/go/
> 
> > These are the official icons. Just read the Brand Guidelines lol, but okay
> 
> @Fedox-die-Ente why did you close the PR?
> 
> The issue you raised is totally fine as soon as we don't set a non-official icon by another non-official one, that's the point I'm trying to make

I thought you didn't care, yeah um, let me quickly put in the “real real” ones from Discord and GitHub, the pure svg ones, so we don't have to import an external library for the icons. Just in case they change.

**Comment by Fedox-die-Ente** [comment]
image
Okay the logo from github is weird on my end

**Comment by abernier** [comment]
for gh I'd go with https://react-icons.github.io/react-icons/icons/go/ since it is maintained "officially" by GitHub

image

for Discord, you can copy/paste a 24x24 svg icon to components/icon.tsx

**Pull request closed without merging**
